// examples/helia-nextjs/components/ipfs.jsx
import { createHelia } from 'helia'
import { React, useState, useEffect } from 'react'

const IpfsComponent = () => {
  const [id, setId] = useState(null)
  const [helia, setHelia] = useState(null)
  const [isOnline, setIsOnline] = useState(false)

  useEffect(() => {
    const init = async () => {
      if (helia) {
        return
      }

      const heliaNode = await createHelia()

      const nodeId = heliaNode.libp2p.peerId.toString()
      const nodeIsOnline = heliaNode.libp2p.status === 'started'

      setHelia(heliaNode)
      setId(nodeId)
      setIsOnline(nodeIsOnline)
    }

    init()
  }, [helia])

  if (!helia || !id) {
    return <h4>Starting Helia...</h4>
  }

  return (
    <div>
      <h4 data-test='id'>ID: {id.toString()}</h4>
      <h4 data-test='status'>Status: {isOnline ? 'Online' : 'Offline'}</h4>
    </div>
  )
}

export default IpfsComponent

// examples/helia-angular/src/app/ipfs.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { createHelia } from 'helia';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})

export class IPFSComponent implements OnInit {
  title = 'helia-angular';
  id: string | null = null;
  isOnline = false;
  helia: any = null;

  async ngOnInit() {
    if (this.helia) return;

    try {
      const heliaNode = await createHelia();
      const nodeId = heliaNode.libp2p.peerId.toString();
      const nodeIsOnline = heliaNode.libp2p.status === 'started';

      this.helia = heliaNode;
      this.id = nodeId;
      this.isOnline = nodeIsOnline;
    } catch (error) {
      console.error('Error initializing Helia:', error);
    }
  }
}
